### ISSUE TITLE
fix name and description

### ISSUE THREAD

**Issue by nonchip** [ncorgan/bgblink-dissector#1]
this is not the "Nintendo Game Boy Link Cable protocol", but the BGB emulator link and remote control protocol. the Nintendo DMG Link Cable is a full-duplex synchronous serial port and doesn't even know what a joypad event is.

**Comment by ncorgan** [comment]
Hm, I haven't looked at this repo for a while.

Libwireshark seems to have changed enough since I wrote this that a simple sed won't solve things, unfortunately, but when I get the time, it should be a fairly simple fix.

Thanks for the correction.
